### ISSUE TITLE
Added a hi-res weapon pack for your Wolf3D-TC-3.0

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#7]
Not exactly an "issue" but just wanted to let you know that...
since I didn't like too small and low-res player weapons I've just created a mod for you excellent Wolf3D-TC-3.0. Details and link to the file: 
https://www.reddit.com/r/Wolfenstein/comments/i2whfk/does_wolfenstein_3d_total_conversion_work_with/hybqmh7/?utm_source=reddit&utm_medium=web2x&context=3 

![Screenshot_Wolf3d_20220225_023715](https://user-images.githubusercontent.com/8591462/155642801-e46155d9-db16-455f-a601-1d82148ee517.png)
![Screenshot_Wolf3d_20220225_023733](https://user-images.githubusercontent.com/8591462/155642805-35e45aa8-ab19-4af1-811d-ffc7104f5ffb.png)
![Screenshot_Wolf3d_20220225_023733_01](https://user-images.githubusercontent.com/8591462/155642807-74610599-2f77-4fc2-88a5-3a9fe332f814.png)
![Screenshot_Wolf3d_20220225_023739](https://user-images.githubusercontent.com/8591462/155642809-9498b25a-f6f0-4728-b3c0-e478a41660f9.png)

**Comment by mrmatteastwood** [comment]
Sick! This looks great. I really hope @AFADoomer finds the time and motivation one day to iron out the few remaining issues with this fantastic TC. I really love the work he's doing here and would be very excited to play this again, especially with access to the SOD missions.

**Comment by Hexaae** [comment]
Yep, runs great. Just a few minor things to correct/improve and add SOD missions too 😉
I hope @AFADoomer will release an update soon...

**Comment by Hexaae** [comment]
New edition for current GZDoom 4.8.2+ and Wolf3D-TC-3.0:
https://1drv.ms/u/s!ApMUGr0cuN39gpsv5Nk8X-pWO0Vg1Q?e=XWf5Lo

**Comment by liPillON** [comment]
> New edition for current GZDoom 4.8.2+ and Wolf3D-TC-3.0: https://1drv.ms/u/s!ApMUGr0cuN39gpsv5Nk8X-pWO0Vg1Q?e=XWf5Lo

using this with the current Beta4 build might result in issues with weapon sprites' offset 
you might want to check if something need to be fixed in your textures definition

this commit might be related
https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/e437b03822eb560a0389cf80a498d4cd25d2b82c

**Comment by Hexaae** [comment]
Working fine here with latest TC-3.0 (download ZIP and rename it ipk3). What version of GZDoom are you using?

**Comment by Hexaae** [comment]
Looks like a new bug in TC-3.0 as it does the same without my "GZDoom\Better_Weapons_textures.pk3":

![image](https://user-images.githubusercontent.com/8591462/204350127-b03d4e58-7612-4ee1-a5cf-36ed96212fe1.png)

**Comment by AFADoomer** [comment]
Sorry about that.  Should be fixed as of e6dc070a8e6fef732ae4070dc97c69151283bd56.  Missed some parentheses in a logic statement.

For the weapon sprite position issue - also check appearance in the software renderers.  I had to manually add code to adjust the weapon sprite position because the software renderer was showing sprites at a different height than hardware - not sure why.  This may require adjustment on your end.

**Comment by Hexaae** [comment]
Ok, this should be fine (have had to adjust only weapon 4 Chaingun):
https://1drv.ms/u/s!ApMUGr0cuN39grs9Pb83KxqrUikzyA?e=2TnZa9

**Comment by Hexaae** [comment]
V4, this includes also Spear of Destiny and Lost Episodes (Mission Packs) support covering new gun, new machine gun, new flamethrower and new rocket launcher:
https://1drv.ms/u/s!ApMUGr0cuN39grs_1D1FxZywvpyr2g?e=f1jpys 

Let me know if you find non-replace weapons or bugs.

**Comment by Hexaae** [comment]
V4 blue version: lore friendly bluish colors for new gun and new machine gun (Spear of Destiny and Lost Episodes):
https://1drv.ms/u/s!ApMUGr0cuN39grtA4vvMKcpi3D0S3g?e=W77iSv

**Comment by liPillON** [comment]
when using "screenblocks=11" AND ("vid_rendermode=1" OR "vid_rendermode=4") the sprite offset issue is still present in Better Weapons pack V4 

i'm using the latest gzdoom git autobuild available at this moment
https://github.com/ZDoom/gzdoom/actions/runs/3559753795

and the latest Wolf3D TC master
https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/926aa46fd98bbdfda914f25b6d4e50027ec876ed


![Screenshot_Wolf3D_20221129_135600](https://user-images.githubusercontent.com/48625273/204534962-d64372ed-24e4-4abb-81ec-07294f3affdf.png)
![Screenshot_Wolf3D_20221129_135602](https://user-images.githubusercontent.com/48625273/204534967-070edd3a-3e39-4e12-9952-e3a00f52e6b9.png)
![Screenshot_Wolf3D_20221129_135557](https://user-images.githubusercontent.com/48625273/204534970-cad36841-924f-4a13-8fe9-a84ecf4657b8.png)
![Screenshot_Wolf3D_20221129_135559](https://user-images.githubusercontent.com/48625273/204534975-44f3e242-9f41-4d41-954c-2553f33b1324.png)

**Comment by Hexaae** [comment]
Uh, I never played with anything less than fullscreen (screenblocks=12). The strange thing is that using smaller screenblocks (using the two keyboard keys after 0) in 1920x1080 16:9 the only badly positioned weapons are knives and chaingun. I see in your screenshot all weapons offset is wrong, mmh...

**Comment by Hexaae** [comment]
Oh, even without my new weapons sprites, also original weapons get misplaced:
![20221129153906_1](https://user-images.githubusercontent.com/8591462/204558677-f6d8ca84-1146-4cbb-b808-dc0f692d90d0.jpg)

**Comment by AFADoomer** [comment]
Ugh.  And this happens only at certain resolutions...  If I play at fullscreen (with st_scale set to 1 and screenblocks of 9 like you have) the sprites are aligned like in your picture, but if I play in windowed mode with the same settings, everything is fine...

**Comment by AFADoomer** [comment]
This should be fixed in b4de753b1ece0b90b7852953c6e07e13936ea356.

You'll probably have to tweak your sprite Y offsets...

**Comment by Hexaae** [comment]
- wolfflamethrower
- wolfrocketlauncher
seem to keep constant 1:1 size, even if I change XScale x YScale y. The other weapons are resized (bigger) and are ok.

**Comment by liPillON** [comment]
looks good here!
I'm using the latest build from GZDoom's master branch and the latest Wolf3D-TC master archive
Thank you

**Comment by Hexaae** [comment]
@liPillON 
How did you enable dithered ground and ceiling?

**Comment by AFADoomer** [comment]
Set the 'g_useflats' CVar to 1.  I think I also added it to the menu...

**Comment by Hexaae** [comment]
LOL, it was under Controls > Use floor/ceiling textures ✔ but I was looking for it in sub-menus.

**Comment by Hexaae** [comment]
Updated V5blue using as default blue/cyan original color of _flamethrower_ pickup sprite.
Redownload the above link. As always, you can switch to standard grey changing WSPR1436÷WSPR1439 to WSPR0436÷WSPR0439 in the **textures.txt**.

**Comment by liPillON** [comment]
the onedrive link does not seems to work at this time
could you please upload the archive it here as an attachment?

**Comment by Hexaae** [comment]
Works fine here the link in [msg #7](https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/7#issuecomment-1333483991)
Tested with another browser without cookies too.

**Comment by Hexaae** [comment]
UPDATE
V6blue: was missing the Lost Episodes' _wolfchaingunlost_ (blue variant WSPR1431÷WSPR1435 in **textures.txt**)
Still the same [download link](https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/7#issuecomment-1333483991).

**Comment by AFADoomer** [comment]
I'm sorry, I added some additional logic recently so that the extra weapon scaling only affects 64x64 weapon sprites...  This makes your weapons now too small - reverting to the older version gives proper scale, though the Y offsets need to be adjusted.

**Comment by Hexaae** [comment]
Argh...
Ok, here is the new one compatible with latest update: https://1drv.ms/u/s!ApMUGr0cuN39grxcBW7zyTpcSmbVzA?e=KjTc6b (V6blue).
BTW, did you slow down rocket missle speed?

**Comment by eierfrucht** [comment]
> Not exactly an "issue" but just wanted to let you know that... since I didn't like too small and low-res player weapons I've just created a mod for you excellent Wolf3D-TC-3.0. Details and link to the file: https://www.reddit.com/r/Wolfenstein/comments/i2whfk/does_wolfenstein_3d_total_conversion_work_with/hybqmh7/?utm_source=reddit&utm_medium=web2x&context=3
> 
> 📦**Latest version:** [#7 (comment)](https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/7#issuecomment-1333483991)
> 
> ![Screenshot_Wolf3d_20220225_023715](https://user-images.githubusercontent.com/8591462/155642801-e46155d9-db16-455f-a601-1d82148ee517.png) ![Screenshot_Wolf3d_20220225_023733](https://user-images.githubusercontent.com/8591462/155642805-35e45aa8-ab19-4af1-811d-ffc7104f5ffb.png) ![Screenshot_Wolf3d_20220225_023733_01](https://user-images.githubusercontent.com/8591462/155642807-74610599-2f77-4fc2-88a5-3a9fe332f814.png) ![Screenshot_Wolf3d_20220225_023739](https://user-images.githubusercontent.com/8591462/155642809-9498b25a-f6f0-4728-b3c0-e478a41660f9.png)
 
Thanks I'm loving it.

Care to port this cosmetic upgrade?

https://dhw.wolfenstein3d.com/viewtopic.php?t=7566

It looks and sounds pretty cool: https://youtu.be/sjlV0GVLWwg

**Comment by Hexaae** [comment]
Nice! But isn't it a bit overkill?
I like small improvements, otherwise I wouldn't have made this mod but... seriously, if you want something that looks/sounds more modern better to play games like Prodeus IMHO

**Comment by eierfrucht** [comment]
I've played through the entire game on LZWolf and it felt fantastic, like what Wolf3D would have looked like if it released in 1995/1996. Definitely not overkill because the asset resolution stays the same. Just a grittier look / sound.

> better to play recent games like Prodeus or Ion Fury IMHO

I'm actually very keen on Doom II TCs and Build engine based games and their mods, I love 'em, still doesn't quite scratch the wolf3d itch.

**Comment by eierfrucht** [comment]
By the way, check out  [Discipline](https://www.moddb.com/mods/discipline) — it’s the pinnacle of wolf3d mapping all the while completely free of any non-vanilla mechanics or entities. It also has a [cosmetic upgrade](https://youtu.be/tOfHUikUClE) that introduces sector-based lighting and floor/ceiling tiling, making for a moody atmosphere. If there's one fan made episode to ever get ported for this TC, that should be it.

**Comment by Hexaae** [comment]
Nice. Not sure if these cosmetic updates can be ported to this AFAdoomer TC though since they are based on specific Wolf3D ports...

**Comment by eierfrucht** [comment]
The «baseline» wolf3d one is a plain asset-and-palette replacer + two specific lines for each level in source port-specific format pointing to ceiling / floor textures + one line setting the ambient lighting level. The latest master branch of the TC (probably the public release, too) already has different level-specific ceilings and floors toggleable in the options, perhaps that was copied over from the cosmetic upgrade (or made in imitation of it)

The «discipline» cosmetic upgrade is more complex: it has a custom ceiling / floor texture AND lighting level specified for each individual tile in a level, and also adds actual circular spotlights under the lamps. These features are exclusive to LZwolf.

Throwing out some of that info enables the upgrade to be used with the less feature-rich ECwolf instead of LZwolf. Given that lighting works differently in Gzdoom and is all about sectors (and simetimes dynamic lights), not tiles, this aspect of the cosmetic upgrades is lost upon GZDoom.

The cosmetic upgrades provide no extra rotation sprites for the bosses (TC has that mod integrated, but turned off by default)

**Comment by stevenvachon** [comment]
It'd be great if we could select which sprites--for weapons, enemies and objects--we'd like to use; between the original, 3DO and Jaguar versions. You can extract them using wolfextractor which comes with Wolfenstein 3D Redux.

**Comment by stevenvachon** [comment]
It'd be great if we could select which sprites--for weapons, enemies and objects--we'd like to use; between the original, 3DO and Jaguar versions.
